### ISSUE TITLE
Three issues in FreePBX 12:  Unsigned module, bad System Status page reports, and appears in top menu bar rather than Applications menu

### ISSUE THREAD

**Issue by tv21** [POSSA/freepbx-dialplan-injection#8]
I had a small project where I needed to inject about four lines of dialplan into the incoming call flow, and I remembered the Dialplan Injection module and thought that if I could find it, it would be ideal.  Obviously I found it because I'm here, and I installed it into FreePBX 12 and it works great, but there are two issues.

First, FreePBX complains about it being unsigned - I barely had it installed and got an email from the system about it.  I found the page at http://wiki.freepbx.org/pages/viewpage.action?pageId=29753662 but since I am not a programmer I don't see any way to disable the signature checking on this one module.  The only thing I can do is disable module signature checking, which I hate doing but then I also hate being nagged about something I can't do anything about, and I trust modules that come from the POSSA repository.  So if there is any way you could somehow get it signed, that would be great, but if not I'll just disable the signature checking, unless you can tell me how to get FreePBX to ignore this module when it is doing signature checking.

The second issue is that even though the dialplan injection works fine, the System Status page reports that your Dialplan Injections are bad destinations.  But if you go to the pages that use the Dialplan Injections as destinations, the destinations do not appear in red as a bad destination normally would, and the destinations continue to work.

The third minor issue is that after it is installed, it appears as a button on the top menu bar, to the right of the UCP button, rather than in in the Applications dropdown where it probably belongs.  This is just a minor cosmetic thing and does not appear to affect the operation of the module, but if it's an easy fix it would be nice if it could be done.  

Thank you very much for keeping this module available,  It just makes things a little easier, since it gives the ability to insert a chunk of dialplan and then pick a destination.

**Comment by lgaetz** [comment]
This module has received almost no code additions by POSSA members, it is just stored here to prevent it from disappearing entirely from the 'net. Some day, a kind soul may devote some effort to fixes, but until that day comes we will have to live with its quirks.
1. Module signing is a problem, and even more so for this module. The original dev is gone, and it is not at all clear at this point under which license (if any) it was released. 
2. The bad destination issue is reported already in ticket #6 
3. I am not seeing the menu issue you report. What version of the module are you using and what version of FreePBX?

**Comment by lgaetz** [comment]
The commit above fixes the menu issue, download from the `working` branch until it gets published.Closing this ticket as the bad destination is noted in ticket #6 and module signing will be dealt with by other means.
